# Generated by Django 3.2.16 on 2023-12-18 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20231217_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'verbose_name': 'Связь Ингредиент-Рецепт', 'verbose_name_plural': 'Связи Ингредиент-Рецепт'},
        ),
    ]
